import { type Project, type Phase } from "./types";

export const defaultPhases: Phase[] = [
  {
    _id: "phase-00",
    phaseNumber: "00",
    phaseTitle: "The Vision",
    description: "The vision and DNA of the project book.",
    whatItIs: "The project intent, typographic mood, and color palette.",
    whatItContains: "Strong quote, moodboard, master materials, project manifesto.",
    layoutType: "Fullscreen",
    quote: "Every project begins with an atmosphere, not a form.",
  },
  {
    _id: "phase-01",
    phaseTitle: "The Spirit",
    phaseNumber: "01",
    description: "The city and exterior spirit.",
    whatItIs: "The connection between the building and the outside world.",
    whatItContains: "City references, landmarks, icons, context mood.",
    layoutType: "Horizontal Gallery",
  },
  {
    _id: "phase-02",
    phaseNumber: "02",
    phaseTitle: "The Human Trace",
    description: "The human factor and daily life.",
    whatItIs: "Evidence that someone lives, works, or moves through the space.",
    whatItContains: "Objects, hands, books, glasses, fabric, and small signs of use.",
    layoutType: "Split Text Image",
  },
  {
    _id: "phase-03",
    phaseNumber: "03",
    phaseTitle: "The Detail",
    description: "Material macros and construction details.",
    whatItIs: "Justification of the material choices.",
    whatItContains: "Material closeups, finishes, joints, and structural solutions.",
    layoutType: "Material Study",
  },
  {
    _id: "phase-04",
    phaseNumber: "04",
    phaseTitle: "The Experience",
    description: "Main architectural views and hero shots.",
    whatItIs: "Validation of the architectural space.",
    whatItContains: "Main renders, key views, hero images, and animation stills.",
    layoutType: "Fullscreen",
  },
  {
    _id: "phase-05",
    phaseNumber: "05",
    phaseTitle: "The Synthesis",
    description: "Closing visual index.",
    whatItIs: "A complete visual summary of the work.",
    whatItContains: "Secondary spaces, 3x3 grids, 4x4 grids, and contact-sheet layouts.",
    layoutType: "Contact Sheet",
  },
];

export const placeholderProjects: Project[] = [
  {
    _id: "proj-01",
    title: "The Coastal House",
    slug: "the-coastal-house",
    collectionLabel: "Residential Collection",
    subtitle: "A private coastal home shaped through light, shadow, and quiet material tension.",
    country: "USA",
    city: "Miami",
    year: "2025",
    projectType: "Residential",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Sales and stakeholder approval",
    featured: true,
    phases: defaultPhases,
  },
  {
    _id: "proj-02",
    title: "Maison Lumiere",
    slug: "maison-lumiere",
    collectionLabel: "Hospitality Collection",
    subtitle: "A boutique hospitality project built around softness, ritual, and evening light.",
    country: "France",
    city: "Paris",
    year: "2025",
    projectType: "Hospitality",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Marketing launch",
    featured: true,
    phases: defaultPhases,
  },
  {
    _id: "proj-03",
    title: "The Garden School",
    slug: "the-garden-school",
    collectionLabel: "Education Collection",
    subtitle: "A learning space where landscape, play, and daily movement become part of the story.",
    country: "Germany",
    city: "Berlin",
    year: "2024",
    projectType: "Education",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Stakeholder approval",
    featured: false,
    phases: defaultPhases,
  },
  {
    _id: "proj-04",
    title: "Riverside Tower",
    slug: "riverside-tower",
    collectionLabel: "Residential Collection",
    subtitle: "A vertical residence framed through city views, calm interiors, and crafted detail.",
    country: "USA",
    city: "New York",
    year: "2024",
    projectType: "Residential",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Sales gallery",
    featured: true,
    phases: defaultPhases,
  },
  {
    _id: "proj-05",
    title: "Casa del Sur",
    slug: "casa-del-sur",
    collectionLabel: "Residential Collection",
    subtitle: "A warm private house built around memory, texture, and domestic traces.",
    country: "Argentina",
    city: "Buenos Aires",
    year: "2024",
    projectType: "Residential",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Design development",
    featured: false,
    phases: defaultPhases,
  },
  {
    _id: "proj-06",
    title: "Alpine Rooms",
    slug: "alpine-rooms",
    collectionLabel: "Hospitality Collection",
    subtitle: "A mountain retreat told through timber, silence, snow, and the ritual of return.",
    country: "Switzerland",
    city: "St. Moritz",
    year: "2025",
    projectType: "Hospitality",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Brand storytelling",
    featured: true,
    phases: defaultPhases,
  },
  {
    _id: "proj-07",
    title: "The Civic Room",
    slug: "the-civic-room",
    collectionLabel: "Cultural Collection",
    subtitle: "A public interior shaped as a quiet civic stage for gathering and exchange.",
    country: "Spain",
    city: "Madrid",
    year: "2024",
    projectType: "Cultural",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Competition",
    featured: false,
    phases: defaultPhases,
  },
  {
    _id: "proj-08",
    title: "The Island Residences",
    slug: "the-island-residences",
    collectionLabel: "Residential Collection",
    subtitle: "A residential project where landscape, shade, and slow arrival define the image world.",
    country: "Puerto Rico",
    city: "San Juan",
    year: "2025",
    projectType: "Residential",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Marketing campaign",
    featured: false,
    phases: defaultPhases,
  },
  {
    _id: "proj-09",
    title: "The Clay Hotel",
    slug: "the-clay-hotel",
    collectionLabel: "Hospitality Collection",
    subtitle: "A hotel concept shaped through earth tones, handmade surfaces, and dense vegetation.",
    country: "Mexico",
    city: "Tulum",
    year: "2024",
    projectType: "Hospitality",
    clientName: "Undisclosed",
    clientVisibility: "Undisclosed",
    mainGoal: "Investor presentation",
    featured: false,
    phases: defaultPhases,
  },
] as Project[];
